//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockWebsite.StockServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockServiceReference.StockServiceSoap")]
    public interface StockServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        StockWebsite.StockServiceReference.HelloWorldResponse HelloWorld(StockWebsite.StockServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<StockWebsite.StockServiceReference.HelloWorldResponse> HelloWorldAsync(StockWebsite.StockServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name symbol from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrice", ReplyAction="*")]
        StockWebsite.StockServiceReference.GetPriceResponse GetPrice(StockWebsite.StockServiceReference.GetPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<StockWebsite.StockServiceReference.GetPriceResponse> GetPriceAsync(StockWebsite.StockServiceReference.GetPriceRequest request);
        
        // CODEGEN: Generating message contract since element name symbol from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        StockWebsite.StockServiceReference.GetNameResponse GetName(StockWebsite.StockServiceReference.GetNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        System.Threading.Tasks.Task<StockWebsite.StockServiceReference.GetNameResponse> GetNameAsync(StockWebsite.StockServiceReference.GetNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public StockWebsite.StockServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(StockWebsite.StockServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public StockWebsite.StockServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(StockWebsite.StockServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrice", Namespace="http://tempuri.org/", Order=0)]
        public StockWebsite.StockServiceReference.GetPriceRequestBody Body;
        
        public GetPriceRequest() {
        }
        
        public GetPriceRequest(StockWebsite.StockServiceReference.GetPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string symbol;
        
        public GetPriceRequestBody() {
        }
        
        public GetPriceRequestBody(string symbol) {
            this.symbol = symbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public StockWebsite.StockServiceReference.GetPriceResponseBody Body;
        
        public GetPriceResponse() {
        }
        
        public GetPriceResponse(StockWebsite.StockServiceReference.GetPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetPriceResult;
        
        public GetPriceResponseBody() {
        }
        
        public GetPriceResponseBody(double GetPriceResult) {
            this.GetPriceResult = GetPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetName", Namespace="http://tempuri.org/", Order=0)]
        public StockWebsite.StockServiceReference.GetNameRequestBody Body;
        
        public GetNameRequest() {
        }
        
        public GetNameRequest(StockWebsite.StockServiceReference.GetNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string symbol;
        
        public GetNameRequestBody() {
        }
        
        public GetNameRequestBody(string symbol) {
            this.symbol = symbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public StockWebsite.StockServiceReference.GetNameResponseBody Body;
        
        public GetNameResponse() {
        }
        
        public GetNameResponse(StockWebsite.StockServiceReference.GetNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNameResult;
        
        public GetNameResponseBody() {
        }
        
        public GetNameResponseBody(string GetNameResult) {
            this.GetNameResult = GetNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockServiceSoapChannel : StockWebsite.StockServiceReference.StockServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceSoapClient : System.ServiceModel.ClientBase<StockWebsite.StockServiceReference.StockServiceSoap>, StockWebsite.StockServiceReference.StockServiceSoap {
        
        public StockServiceSoapClient() {
        }
        
        public StockServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockWebsite.StockServiceReference.HelloWorldResponse StockWebsite.StockServiceReference.StockServiceSoap.HelloWorld(StockWebsite.StockServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            StockWebsite.StockServiceReference.HelloWorldRequest inValue = new StockWebsite.StockServiceReference.HelloWorldRequest();
            inValue.Body = new StockWebsite.StockServiceReference.HelloWorldRequestBody();
            StockWebsite.StockServiceReference.HelloWorldResponse retVal = ((StockWebsite.StockServiceReference.StockServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockWebsite.StockServiceReference.HelloWorldResponse> StockWebsite.StockServiceReference.StockServiceSoap.HelloWorldAsync(StockWebsite.StockServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockWebsite.StockServiceReference.HelloWorldResponse> HelloWorldAsync() {
            StockWebsite.StockServiceReference.HelloWorldRequest inValue = new StockWebsite.StockServiceReference.HelloWorldRequest();
            inValue.Body = new StockWebsite.StockServiceReference.HelloWorldRequestBody();
            return ((StockWebsite.StockServiceReference.StockServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockWebsite.StockServiceReference.GetPriceResponse StockWebsite.StockServiceReference.StockServiceSoap.GetPrice(StockWebsite.StockServiceReference.GetPriceRequest request) {
            return base.Channel.GetPrice(request);
        }
        
        public double GetPrice(string symbol) {
            StockWebsite.StockServiceReference.GetPriceRequest inValue = new StockWebsite.StockServiceReference.GetPriceRequest();
            inValue.Body = new StockWebsite.StockServiceReference.GetPriceRequestBody();
            inValue.Body.symbol = symbol;
            StockWebsite.StockServiceReference.GetPriceResponse retVal = ((StockWebsite.StockServiceReference.StockServiceSoap)(this)).GetPrice(inValue);
            return retVal.Body.GetPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockWebsite.StockServiceReference.GetPriceResponse> StockWebsite.StockServiceReference.StockServiceSoap.GetPriceAsync(StockWebsite.StockServiceReference.GetPriceRequest request) {
            return base.Channel.GetPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockWebsite.StockServiceReference.GetPriceResponse> GetPriceAsync(string symbol) {
            StockWebsite.StockServiceReference.GetPriceRequest inValue = new StockWebsite.StockServiceReference.GetPriceRequest();
            inValue.Body = new StockWebsite.StockServiceReference.GetPriceRequestBody();
            inValue.Body.symbol = symbol;
            return ((StockWebsite.StockServiceReference.StockServiceSoap)(this)).GetPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockWebsite.StockServiceReference.GetNameResponse StockWebsite.StockServiceReference.StockServiceSoap.GetName(StockWebsite.StockServiceReference.GetNameRequest request) {
            return base.Channel.GetName(request);
        }
        
        public string GetName(string symbol) {
            StockWebsite.StockServiceReference.GetNameRequest inValue = new StockWebsite.StockServiceReference.GetNameRequest();
            inValue.Body = new StockWebsite.StockServiceReference.GetNameRequestBody();
            inValue.Body.symbol = symbol;
            StockWebsite.StockServiceReference.GetNameResponse retVal = ((StockWebsite.StockServiceReference.StockServiceSoap)(this)).GetName(inValue);
            return retVal.Body.GetNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockWebsite.StockServiceReference.GetNameResponse> StockWebsite.StockServiceReference.StockServiceSoap.GetNameAsync(StockWebsite.StockServiceReference.GetNameRequest request) {
            return base.Channel.GetNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockWebsite.StockServiceReference.GetNameResponse> GetNameAsync(string symbol) {
            StockWebsite.StockServiceReference.GetNameRequest inValue = new StockWebsite.StockServiceReference.GetNameRequest();
            inValue.Body = new StockWebsite.StockServiceReference.GetNameRequestBody();
            inValue.Body.symbol = symbol;
            return ((StockWebsite.StockServiceReference.StockServiceSoap)(this)).GetNameAsync(inValue);
        }
    }
}
